version: '3.8'
services:
  game:
    build: .
    volumes:
      - ./:/app
    tty: true
    command: []
  test:
    build: .
    volumes:
      - ./:/app
    entrypoint: ["vendor/bin/phpunit", "-c", "phpunit.xml.dist"]
